stricter verify + unpack
utily/authly pull request #91
Opened 2024-05-08 09:08 UTC by EliasEriksson

* Verification always fails if no algorithm is specified
* Implemented `Verifier.unpack()` method
* Refactored out common logic from unpack / verify into two new private method `Verifier.decode(...)` and `Verifier.transform(...)`

The stricter verification is backwards incompatible.

2024-05-08 09:32 UTC, EliasEriksson reviewed
self check

2024-05-13 11:49 UTC, simonmika requested changes

2024-05-13 11:49 UTC, simonmika commented on Verifier.ts
> +		if (splitted?.length != 3)
What if we use tokens without signature?

2024-05-13 11:49 UTC, simonmika commented on Verifier.ts
> +					payload.exp = Math.floor(payload.exp / 1000)
These where used for backwards compatibility with a very early version that contained timestamps in milliseconds. We might not need this anymore.

2024-05-13 11:49 UTC, simonmika commented on Verifier.ts
> +		else if (!this.verifyAudience(decoded.payload.aud, audience))
They are all the same case use `||` and single assignment.

2024-05-13 12:13 UTC, merged